### ISSUE TITLE
ТС пастер

### ISSUE THREAD

**Issue by senko1337** [easyminerhost/minerhost#1]
- [ ]

**Comment by senko1337** [comment]
почему репу создал предшественник обезьяны

**Comment by easyminerhost** [comment]
почему senko1337 мамонт

**Comment by senko1337** [comment]
![243066_10150203770227029_260283_o](https://user-images.githubusercontent.com/59355976/143913764-c7cddf86-1dfd-47b1-a72f-838a2f6ce77f.jpg)
